const component = (name: string, options: Record<string, unknown> = {}) => ({ component: name, options })

export const Head = () => component("Head")
export const PageTitle = () => component("PageTitle")
export const Spacer = () => component("Spacer")
export const Search = () => component("Search")
export const Explorer = () => component("Explorer")
export const Breadcrumbs = () => component("Breadcrumbs")
export const Backlinks = () => component("Backlinks")
export const Graph = () => component("Graph")
export const TableOfContents = () => component("TableOfContents")
export const ArticleTitle = () => component("ArticleTitle")
export const ContentMeta = () => component("ContentMeta")
export const TagList = () => component("TagList")
export const DesktopOnly = (child: unknown) => component("DesktopOnly", { child })
export const Footer = (options: Record<string, unknown> = {}) => component("Footer", options)
