const plugin = (name: string, options: Record<string, unknown> = {}) => ({ name, options })

export const FrontMatter = () => plugin("FrontMatter")
export const CreatedModifiedDate = () => plugin("CreatedModifiedDate")
export const SyntaxHighlighting = () => plugin("SyntaxHighlighting")
export const ObsidianFlavoredMarkdown = () => plugin("ObsidianFlavoredMarkdown")
export const GitHubFlavoredMarkdown = () => plugin("GitHubFlavoredMarkdown")
export const TableOfContents = () => plugin("TableOfContents")
export const CrawlLinks = (options: Record<string, unknown> = {}) => plugin("CrawlLinks", options)
export const Description = () => plugin("Description")
export const Latex = () => plugin("Latex")
export const RemoveDrafts = () => plugin("RemoveDrafts")
export const AliasRedirects = () => plugin("AliasRedirects")
export const ComponentResources = () => plugin("ComponentResources")
export const ContentPage = () => plugin("ContentPage")
export const FolderPage = () => plugin("FolderPage")
export const TagPage = () => plugin("TagPage")
export const ContentIndex = (options: Record<string, unknown> = {}) => plugin("ContentIndex", options)
export const Assets = () => plugin("Assets")
export const Static = () => plugin("Static")
export const NotFoundPage = () => plugin("NotFoundPage")
